### ISSUE TITLE
How to sendMessageWithMention

### ISSUE THREAD

**Issue by GoneawayCherry** [kaoru-nishida/LineJava#3]
Can solve it?

**Comment by HelloTan** [comment]
Maybe

client.sendMessage(new Message().setTo(op.message.to).setContentType(????).setContentMetadata(????));

You can check ==> LineClient.java

**Comment by GoneawayCherry** [comment]
I tried, but not

Mention is like this format <String, List<Map<String, String>>>

But ContentMetadata can only support <String, String>

**Comment by GoneawayCherry** [comment]
Oh my god, 私はちょうどPy3の言及を使用して実際に<String、String>、多分私が間違ったJavaを使用したことがわかった、ごめんなさい

**Comment by HelloTan** [comment]
Not problem ✌️

**Comment by tomo0611** [comment]
I will add it.
I'm trying it.

**Comment by tomo0611** [comment]
I added it and pushed it.
Please update,and you can use sendMessageWithMention() function
